image: intension/docker-dind-maven:3.8.5-r0-openjdk17

stages:
  - build
  - unit-testing
  - integration-testing

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
    - target   

unit-testing-job:
  stage: unit-testing
  dependencies: 
    - build-job  
  script:
    - echo "Running unit test... TODO!"

integration-testing-job:
  stage: integration-testing
  dependencies:
    - unit-testing-job
  script:
    - echo "Running integration test..."
    - mvn verify
