image: intension/docker-dind-maven:3.8.5-r0-openjdk17

stages:
  - build
  - test
  - verify

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
    - target   

test-job:
  stage: test
  dependencies: 
    - build-job  
  script:
    - echo "Running tests... TODO!"

verify-job:
  stage: verify
  dependencies:
    - test-job
  script:
    - echo "Running verify..."
    - mvn verify
