version: "3"

services:
  sonarqube:
    image: sonarqube:8.9.8-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  # db:
  #   image: postgres:13.1
  #   container_name: db
  #   hostname: db
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - pg_db:/var/lib/postgresql
  #     - pg_data:/var/lib/postgresql/data
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536

volumes:
  # pg_db:
  #   driver: local
  # pg_data:
  #   driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp: